version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/
hooks:
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 10
      runas: ec2-user
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 10
      runas: ec2-user
  ValidateService:
    - location: scripts/ValidateService.sh
      timeout: 10
      runas: ec2-user
