name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # or any version your project requires

    - name: Install dependencies
      run: npm install

    - name: Run tests
      #run: npm test
      # Remove or comment out the following line if no test is needed
      run: echo "Skipping tests"

    - name: Build project
      run: npm run build  # or the build command your project uses

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USERNAME: ubuntu
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 600 key.pem
        scp -i key.pem -o StrictHostKeyChecking=no ./next/* $USERNAME@$HOST:/path/to/deploy
        ssh -i key.pem -o StrictHostKeyChecking=no $USERNAME@$HOST 'cd /path/to/deploy && npm install --production && pm2 restart your-app'
