name: Deploy Next.js Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Upload production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nextjs-build
        path: .next

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download production artifacts
      uses: actions/download-artifact@v2
      with:
        name: nextjs-build
        path: .next

    - name: Ensure .next directory exists
      run: ls -la .next

    - name: Deploy to EC2 (Next.js Build Files)
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ec2-user@ec2-3-145-166-99.us-east-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "./.next/*"
        target: "/home/ec2-user/lmjtm-prod/.next"
        port: 22
        timeout: 30s
        debug: true
        command_timeout: 10m
        use_insecure_cipher: false
        rm: false
        strip_components: 0
        overwrite: false
        proxy_port: 22
        proxy_timeout: 30s
        proxy_use_insecure_cipher: false

    - name: Copy other necessary files (e.g., package.json)
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ec2-user@ec2-3-145-166-99.us-east-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "./package.json"
        target: "/home/ec2-user/lmjtm-prod"
        port: 22
        timeout: 30s
        debug: true
        command_timeout: 10m
        use_insecure_cipher: false
        rm: false
        strip_components: 0
        overwrite: false
        proxy_port: 22
        proxy_timeout: 30s
        proxy_use_insecure_cipher: false

    - name: SSH into EC2 and run commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ec2-user@ec2-3-145-166-99.us-east-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/lmjtm-prod
          ls -la .next
          npm install --production
          npm run start
