name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          .next/cache
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: echo "Skipping tests"

    - name: Build project
      run: npm run build

    - name: Create deployment directory
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USERNAME: ubuntu
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 600 key.pem
        ssh -i key.pem -o StrictHostKeyChecking=no $USERNAME@$HOST 'mkdir -p /treemap'

    - name: List build directory
      run: ls -la .next

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USERNAME: ubuntu
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 600 key.pem
        scp -i key.pem -o StrictHostKeyChecking=no .next/* $USERNAME@$HOST:/treemap
        ssh -i key.pem -o StrictHostKeyChecking=no $USERNAME@$HOST 'cd /treemap && npm install --production && pm2 restart treemap'
