name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          .next/cache
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: echo "Skipping tests"

    - name: Build project
      run: npm run build

    - name: Check if .next directory exists
      run: if [ -d ".next" ]; then echo ".next directory exists"; else echo ".next directory does not exist"; fi

    - name: List project directory
      run: ls -la

    - name: List build directory
      run: ls -la .next
      

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: next-build
        path: .next

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      HOST: ${{ secrets.EC2_HOST }}
      USERNAME: ubuntu

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: next-build

    - name: List downloaded artifacts directory
      run: ls -la

    - name: Create deployment directory
      run: mkdir -p treemap

    - name: List current directory before deploy
      run: ls -la

    - name: Deploy to server
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 600 key.pem
        scp -i key.pem -o StrictHostKeyChecking=no -r .next/* $USERNAME@$HOST:/treemap
        ssh -i key.pem -o StrictHostKeyChecking=no $USERNAME@$HOST 'cd /treemap && npm install --production && pm2 restart treemap'

    - name: Clean up
      run: rm -f key.pem
