name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Upload production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nextjs-build
        path: .next

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download production artifacts
      uses: actions/download-artifact@v2
      with:
        name: nextjs-build

    - name: Deploy to EC2
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "./"  # Transfer the built artifacts
        target: "/home/ec2-user/lmjtm-prod/"
        port: 22
        timeout: 30s

    - name: SSH into EC2 and install dependencies
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/lmjtm-prod
          npm install --production
          npm run start
